/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import dev.aurakai.auraframefx.api.client.models.AgentType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param agentType The type of the AI agent.
 * @param processingState Current processing state of the agent (e.g., \"IDLE\", \"PROCESSING\", \"ERROR\").
 * @param visionState Current vision/awareness state (e.g., \"ACTIVE\", \"MONITORING\", \"SLEEP\").
 * @param lastActivity Timestamp of the last activity.
 * @param currentTask Description of the current task being executed by the agent (if any).
 */
@Serializable

public data class AgentStatus (

    /* The type of the AI agent. */
    @Contextual @SerialName(value = "agentType")
    public val agentType: AgentType,

    /* Current processing state of the agent (e.g., \"IDLE\", \"PROCESSING\", \"ERROR\"). */
    @SerialName(value = "processingState")
    public val processingState: kotlin.String,

    /* Current vision/awareness state (e.g., \"ACTIVE\", \"MONITORING\", \"SLEEP\"). */
    @SerialName(value = "visionState")
    public val visionState: kotlin.String,

    /* Timestamp of the last activity. */
    @Contextual @SerialName(value = "lastActivity")
    public val lastActivity: java.time.OffsetDateTime,

    /* Description of the current task being executed by the agent (if any). */
    @SerialName(value = "currentTask")
    public val currentTask: kotlin.String? = null

) {


}

