/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import dev.aurakai.auraframefx.api.client.models.AgentType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique identifier for the conference room.
 * @param name Name of the conference room.
 * @param orchestrator The AI agent acting as the orchestrator.
 * @param activeAgents List of AI agents currently in the room.
 */
@Serializable

public data class ConferenceRoom (

    /* Unique identifier for the conference room. */
    @Contextual @SerialName(value = "id")
    public val id: java.util.UUID,

    /* Name of the conference room. */
    @SerialName(value = "name")
    public val name: kotlin.String,

    /* The AI agent acting as the orchestrator. */
    @Contextual @SerialName(value = "orchestrator")
    public val orchestrator: AgentType,

    /* List of AI agents currently in the room. */
    @SerialName(value = "activeAgents")
    public val activeAgents: kotlin.collections.List<@Contextual AgentType>

) {


}

