/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import dev.aurakai.auraframefx.api.client.models.AgentType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param roomName Name of the new conference room.
 * @param orchestratorAgent The AI agent designated as the orchestrator for this room.
 */
@Serializable

public data class ConferenceRoomCreateRequest (

    /* Name of the new conference room. */
    @SerialName(value = "roomName")
    public val roomName: kotlin.String,

    /* The AI agent designated as the orchestrator for this room. */
    @Contextual @SerialName(value = "orchestratorAgent")
    public val orchestratorAgent: AgentType

) {


}

