/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param imageUrl URL of the image to describe.
 * @param context Additional context for the image description (optional).
 */
@Serializable

public data class GenerateImageDescriptionRequest (

    /* URL of the image to describe. */
    @SerialName(value = "imageUrl")
    public val imageUrl: kotlin.String,

    /* Additional context for the image description (optional). */
    @SerialName(value = "context")
    public val context: kotlin.String? = null

) {


}

