/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param framework The UI framework (e.g., \"JetpackCompose\", \"XML Layout\").
 * @param description Natural language description of the UI component.
 * @param themeId ID of a specific theme to use for styling.
 */
@Serializable

public data class GenerateUIComponentRequest (

    /* The UI framework (e.g., \"JetpackCompose\", \"XML Layout\"). */
    @SerialName(value = "framework")
    public val framework: GenerateUIComponentRequest.Framework,

    /* Natural language description of the UI component. */
    @SerialName(value = "description")
    public val description: kotlin.String,

    /* ID of a specific theme to use for styling. */
    @SerialName(value = "themeId")
    public val themeId: kotlin.String? = null

) {

    /**
     * The UI framework (e.g., \"JetpackCompose\", \"XML Layout\").
     *
     * Values: JetpackCompose,XMLLayout
     */
    @Serializable
    public enum class Framework(val value: kotlin.String) {
        @SerialName(value = "JetpackCompose") JetpackCompose("JetpackCompose"),
        @SerialName(value = "XMLLayout") XMLLayout("XMLLayout");
    }

}

