/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param generatedText The AI-generated text.
 * @param finishReason Reason for generation completion (e.g., STOP, MAX_TOKENS).
 */
@Serializable

public data class GenerateTextResponse (

    /* The AI-generated text. */
    @SerialName(value = "generatedText")
    public val generatedText: kotlin.String,

    /* Reason for generation completion (e.g., STOP, MAX_TOKENS). */
    @SerialName(value = "finishReason")
    public val finishReason: kotlin.String? = null

) {


}

