/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param uiCode The generated UI component code.
 * @param previewImage URL to an image preview of the generated UI (optional).
 */
@Serializable

public data class GenerateUIComponentResponse (

    /* The generated UI component code. */
    @SerialName(value = "uiCode")
    public val uiCode: kotlin.String,

    /* URL to an image preview of the generated UI (optional). */
    @SerialName(value = "previewImage")
    public val previewImage: kotlin.String? = null

) {


}

