/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import dev.aurakai.auraframefx.api.client.models.AgentType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id Unique ID of the historical task.
 * @param timestamp When the task was executed.
 * @param taskType The type of task.
 * @param agentType The agent that executed the task.
 * @param status 
 * @param summary A brief summary of the task and its outcome.
 */
@Serializable

public data class HistoricalTask (

    /* Unique ID of the historical task. */
    @SerialName(value = "id")
    public val id: kotlin.String,

    /* When the task was executed. */
    @Contextual @SerialName(value = "timestamp")
    public val timestamp: java.time.OffsetDateTime,

    /* The type of task. */
    @SerialName(value = "taskType")
    public val taskType: kotlin.String,

    /* The agent that executed the task. */
    @Contextual @SerialName(value = "agentType")
    public val agentType: AgentType,

    @SerialName(value = "status")
    public val status: HistoricalTask.Status,

    /* A brief summary of the task and its outcome. */
    @SerialName(value = "summary")
    public val summary: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: COMPLETED,FAILED
     */
    @Serializable
    public enum class Status(val value: kotlin.String) {
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "FAILED") FAILED("FAILED");
    }

}

