/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import dev.aurakai.auraframefx.api.client.models.LockScreenConfigAnimation
import dev.aurakai.auraframefx.api.client.models.LockScreenConfigClockConfig
import dev.aurakai.auraframefx.api.client.models.LockScreenConfigHapticFeedback

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Configuration for lock screen customization.
 *
 * @param clockConfig 
 * @param animation 
 * @param hapticFeedback 
 */
@Serializable

public data class LockScreenConfig (

    @Contextual @SerialName(value = "clockConfig")
    public val clockConfig: LockScreenConfigClockConfig? = null,

    @Contextual @SerialName(value = "animation")
    public val animation: LockScreenConfigAnimation? = null,

    @Contextual @SerialName(value = "hapticFeedback")
    public val hapticFeedback: LockScreenConfigHapticFeedback? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

