/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabled 
 * @param intensity 
 */
@Serializable

public data class LockScreenConfigHapticFeedback (

    @SerialName(value = "enabled")
    public val enabled: kotlin.Boolean? = null,

    @SerialName(value = "intensity")
    public val intensity: kotlin.Int? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

