/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param customTextColorEnabled 
 * @param customTextColor Hex color code (e.g., \"#00FFCC\")
 * @param customTextSizeEnabled 
 * @param customTextSize Text size in sp.
 */
@Serializable

public data class LockScreenConfigClockConfig (

    @SerialName(value = "customTextColorEnabled")
    public val customTextColorEnabled: kotlin.Boolean? = null,

    /* Hex color code (e.g., \"#00FFCC\") */
    @SerialName(value = "customTextColor")
    public val customTextColor: kotlin.String? = null,

    @SerialName(value = "customTextSizeEnabled")
    public val customTextSizeEnabled: kotlin.Boolean? = null,

    /* Text size in sp. */
    @SerialName(value = "customTextSize")
    public val customTextSize: kotlin.Float? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

