/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code The authorization code received from the OAuth provider.
 * @param state The state parameter to prevent CSRF attacks.
 */
@Serializable

public data class OAuthCallbackRequest (

    /* The authorization code received from the OAuth provider. */
    @SerialName(value = "code")
    public val code: kotlin.String,

    /* The state parameter to prevent CSRF attacks. */
    @SerialName(value = "state")
    public val state: kotlin.String? = null

) {


}

