/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param authUrl The URL the user should be redirected to for authentication.
 */
@Serializable

public data class OAuthStartResponse (

    /* The URL the user should be redirected to for authentication. */
    @SerialName(value = "authUrl")
    public val authUrl: kotlin.String

) {


}

