/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import dev.aurakai.auraframefx.api.client.models.AgentMessage

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param status Status of the orchestration (e.g., \"INITIATED\", \"PROCESSING\", \"COMPLETED\", \"FAILED\").
 * @param messages Messages/responses from the orchestrator and involved agents.
 */
@Serializable

public data class OrchestrationResponse (

    /* Status of the orchestration (e.g., \"INITIATED\", \"PROCESSING\", \"COMPLETED\", \"FAILED\"). */
    @SerialName(value = "status")
    public val status: kotlin.String,

    /* Messages/responses from the orchestrator and involved agents. */
    @SerialName(value = "messages")
    public val messages: kotlin.collections.List<AgentMessage>? = null

) {


}

