/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import dev.aurakai.auraframefx.api.client.models.AgentType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param instruction The instruction or query for the orchestrator to manage.
 * @param targetAgents Specific agents to involve in the orchestration (optional).
 */
@Serializable

public data class OrchestrationRequest (

    /* The instruction or query for the orchestrator to manage. */
    @SerialName(value = "instruction")
    public val instruction: kotlin.String,

    /* Specific agents to involve in the orchestration (optional). */
    @SerialName(value = "targetAgents")
    public val targetAgents: kotlin.collections.List<@Contextual AgentType>? = null

) {


}

