/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import dev.aurakai.auraframefx.api.client.models.QuickSettingsConfigLayout
import dev.aurakai.auraframefx.api.client.models.QuickSettingsConfigPadding
import dev.aurakai.auraframefx.api.client.models.QuickSettingsConfigTilesInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Configuration for Quick Settings panel customization.
 *
 * @param layout 
 * @param padding 
 * @param tiles 
 */
@Serializable

public data class QuickSettingsConfig (

    @SerialName(value = "layout")
    public val layout: QuickSettingsConfigLayout? = null,

    @SerialName(value = "padding")
    public val padding: QuickSettingsConfigPadding? = null,

    @SerialName(value = "tiles")
    public val tiles: kotlin.collections.List<@Contextual QuickSettingsConfigTilesInner>? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}

