/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param columns 
 * @param rows 
 */
@Serializable

public data class QuickSettingsConfigLayout (

    @SerialName(value = "columns")
    public val columns: kotlin.Int? = null,

    @SerialName(value = "rows")
    public val rows: kotlin.Int? = null

) {


}

