/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param top 
 * @param bottom 
 * @param horizontal 
 */
@Serializable

public data class QuickSettingsConfigPadding (

    @SerialName(value = "top")
    public val top: kotlin.Int? = null,

    @SerialName(value = "bottom")
    public val bottom: kotlin.Int? = null,

    @SerialName(value = "horizontal")
    public val horizontal: kotlin.Int? = null

) {


}

