/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabled 
 * @param color Hex color code of the notch bar.
 * @param displayMode 
 * @param customImageEnabled 
 * @param customImageUrl 
 */
@Serializable

public data class SystemOverlayConfigNotchBar (

    @SerialName(value = "enabled")
    public val enabled: kotlin.Boolean? = null,

    /* Hex color code of the notch bar. */
    @SerialName(value = "color")
    public val color: kotlin.String? = null,

    @SerialName(value = "displayMode")
    public val displayMode: SystemOverlayConfigNotchBar.DisplayMode? = null,

    @SerialName(value = "customImageEnabled")
    public val customImageEnabled: kotlin.Boolean? = null,

    @SerialName(value = "customImageUrl")
    public val customImageUrl: kotlin.String? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {

    /**
     * 
     *
     * Values: Minimal,Detailed,Hidden
     */
    @Serializable
    public enum class DisplayMode(val value: kotlin.String) {
        @SerialName(value = "Minimal") Minimal("Minimal"),
        @SerialName(value = "Detailed") Detailed("Detailed"),
        @SerialName(value = "Hidden") Hidden("Hidden");
    }

}

