/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import dev.aurakai.auraframefx.api.client.models.AgentType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param taskType The type of task (e.g., \"CONTENT_GENERATION\", \"SYSTEM_OPTIMIZATION\", \"SECURITY_SCAN\").
 * @param agentType The AI agent responsible for the task.
 * @param details Specific parameters for the task, varying by taskType.
 * @param priority 
 */
@Serializable

public data class TaskScheduleRequest (

    /* The type of task (e.g., \"CONTENT_GENERATION\", \"SYSTEM_OPTIMIZATION\", \"SECURITY_SCAN\"). */
    @SerialName(value = "taskType")
    public val taskType: kotlin.String,

    /* The AI agent responsible for the task. */
    @Contextual @SerialName(value = "agentType")
    public val agentType: AgentType,

    /* Specific parameters for the task, varying by taskType. */
    @Contextual @SerialName(value = "details")
    public val details: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @SerialName(value = "priority")
    public val priority: TaskScheduleRequest.Priority? = Priority.NORMAL

) {

    /**
     * 
     *
     * Values: HIGH,NORMAL,LOW
     */
    @Serializable
    public enum class Priority(val value: kotlin.String) {
        @SerialName(value = "HIGH") HIGH("HIGH"),
        @SerialName(value = "NORMAL") NORMAL("NORMAL"),
        @SerialName(value = "LOW") LOW("LOW");
    }

}

