/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param taskId Unique identifier for the task.
 * @param status 
 * @param progress Percentage completion of the task (0-100).
 * @param result The outcome or output of the task (structure varies by taskType).
 * @param errorMessage Error message if the task failed.
 */
@Serializable

public data class TaskStatus (

    /* Unique identifier for the task. */
    @SerialName(value = "taskId")
    public val taskId: kotlin.String,

    @SerialName(value = "status")
    public val status: TaskStatus.Status,

    /* Percentage completion of the task (0-100). */
    @SerialName(value = "progress")
    public val progress: kotlin.Int? = null,

    /* The outcome or output of the task (structure varies by taskType). */
    @Contextual @SerialName(value = "result")
    public val result: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Error message if the task failed. */
    @SerialName(value = "errorMessage")
    public val errorMessage: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: PENDING,IN_PROGRESS,COMPLETED,FAILED,CANCELLED
     */
    @Serializable
    public enum class Status(val value: kotlin.String) {
        @SerialName(value = "PENDING") PENDING("PENDING"),
        @SerialName(value = "IN_PROGRESS") IN_PROGRESS("IN_PROGRESS"),
        @SerialName(value = "COMPLETED") COMPLETED("COMPLETED"),
        @SerialName(value = "FAILED") FAILED("FAILED"),
        @SerialName(value = "CANCELLED") CANCELLED("CANCELLED");
    }

}

