package dev.aurakai.auraframefx.data.offline

import kotlinx.serialization.Serializable

// --- New Data Class Definition ---
@Serializable
public data class SystemMonitoringConfig(
    public val enabled: Boolean = false,
    public val batteryThresholdLow: Int = 20, // Percentage
    public val batteryOptimizationEnabled: Boolean = false,
    public val networkChangeMonitoringEnabled: Boolean = false,
    public val appUsageAnomalyDetectionEnabled: Boolean = false,
    public val securityScanIntervalHours: Int = 24,
    // TODO: Add more monitoring parameters as needed
)

// --- Placeholder definitions for other data classes referenced by CriticalOfflineData ---
// These should be fleshed out or replaced by actual definitions if they exist elsewhere.

@Serializable
public data class OfflineAIConfig(
    public val defaultAuraResponses: Map<String, String> = emptyMap(),
    public val defaultKaiResponses: Map<String, String> = emptyMap(), // Added based on KaiAIService logic
    public val lastSyncTimestamp: Long = 0L,
    // Add other AI-related offline configurations if needed
)

@Serializable
public data class OfflineUserPreferences(
    public val theme: String = "system_default",
    public val preferredUnits: String = "metric",
    // Add other user preferences
)

@Serializable
public data class OfflineConversationHistory(
    public val messages: List<String> = emptyList(), // Simplified, could be List<AgentMessagePlaceholder>
    // Add other history-related fields
)

@Serializable
public data class OfflineUIConfigs(
    public val showTooltips: Boolean = true,
    public val compactMode: Boolean = false,
    // Add other UI configuration settings
)

@Serializable
public data class ContextualMemory(
    public val lastUpdateTimestamp: Long = 0,
    public val keyInsights: Map<String, String> = emptyMap(), // Key-value pairs for learned facts
    public val userPreferencesDerived: Map<String, String> = emptyMap(), // E.g., "favorite_color": "neon blue"
    public val importantSystemStates: Map<String, String> = emptyMap(), // E.g., "last_boot_time": "...", "network_status": "offline"
    public val recentKeywords: List<String> = emptyList(), // Recently discussed keywords
    public val summaryOfPastInteractions: String = "", // A condensed summary generated by AI
)


// --- CriticalOfflineData definition including the new SystemMonitoringConfig ---
@Serializable
public data class CriticalOfflineData(
    public val lastFullSyncTimestamp: Long = 0,
    public val aiConfig: OfflineAIConfig = OfflineAIConfig(),
    public val userPreferences: OfflineUserPreferences = OfflineUserPreferences(),
    public val conversationHistory: OfflineConversationHistory = OfflineConversationHistory(),
    public val uiConfigs: OfflineUIConfigs = OfflineUIConfigs(),
    public val contextualMemory: ContextualMemory = ContextualMemory(),
    public val systemMonitoring: SystemMonitoringConfig = SystemMonitoringConfig(), // NEW PROPERTY
)
